spring:
  # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

  # 정적 자원 설정(CSS, JS, 이미지)
  web:
    resources:
      staticLocations: file:src/main/resources/static/
# 타임리프 쓸때만 필요

# 파일 업로드 경로 설정
file:
  upload:
    path: ${fileUpload.path}
    url: /upload/