server:
  port: 3000

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

      routes:
        - id: api-service       # 주소 그럴듯하게 맵핑
          uri: lb://api-service
          predicates:
            - Path=/api/v1/**
          filters:
            - RewritePath=/api/v1/?(?<path>.*),/$\{path}


        - id: admin-service     # 관리자 주소 맵핑
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/?(?<path>.*),/$\{path}

# 유레카 설정
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaHost}/eureka/

# 액츄에이터 설정
management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway